import { useEffect, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { pdf } from "@react-pdf/renderer";
import EmployeeReportPDF from "./EmployeeReportPDF";
import Layout from "../../components/Layout";
import PillSelect from "../../components/common/PillSelect";
import PageHeader from "../../components/common/PageHeader";
import KpiCard from "../../components/common/KpiCard";
import ExportPdfButton from "../../components/common/ExportPdfButton";
import "./AutoGeneratedReports.css";

export default function AutoGeneratedReports() {
  const [searchParams] = useSearchParams();
  const [reports, setReports] = useState([]);
  const [selectedId, setSelectedId] = useState(null);
  const [loading, setLoading] = useState(true);

  const reportFromUrl = searchParams.get("report");

  useEffect(() => {
    const fetchReports = async () => {
      try {
        const res = await fetch(
          "http://127.0.0.1:8000/api/employee/E001/monthly-report"
        );
        const data = await res.json();

        // If backend returns a single report object, wrap it in array
        const reportsArray = Array.isArray(data) ? data : [data];
        setReports(reportsArray);

        // Default selection
        const defaultId = reportFromUrl || reportsArray[0]?.id;
        setSelectedId(defaultId);
        setLoading(false);
      } catch (err) {
        console.error("Failed to fetch report:", err);
        setLoading(false);
      }
    };

    fetchReports();
  }, [reportFromUrl]);

  if (loading) return <div>Loading reports...</div>;
  if (!reports.length) return <div>No reports available</div>;

  const selected = reports.find((r) => r.id === selectedId) || reports[0];

  const handleDownload = async () => {
    const name = selected.employee?.name || "Employee";
    const blob = await pdf(
      <EmployeeReportPDF
        report={selected}
        employeeName={name}
        employeeId={selected.employee?.id || ""}
        downloadDate={new Date()}
      />
    ).toBlob();

    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${name}-${selected.month}-Report.pdf`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };

  return (
    <Layout role="employee">
      <div className="empReportsPage">
        <PageHeader
          title={`Monthly Performance Report – ${selected.month}`}
          subtitle={selected.subtitle}
          actions={
            <>
              <PillSelect
                value={selectedId}
                onChange={setSelectedId}
                ariaLabel="Select month report"
                options={reports.map((r) => ({
                  value: r.id,
                  label: r.month,
                }))}
              />

              <ExportPdfButton
                as="button"
                className="downloadBtn"
                onClick={handleDownload}
                label="Export PDF"
              />
            </>
          }
        />

        <section className="kpiRow">
          <KpiCard
            label="Overall Rating"
            value={selected.kpis.rating}
            caption="Based on closure rate & SLA."
          />
          <KpiCard
            label="Complaints Resolved"
            value={selected.kpis.resolved}
            caption="All priorities combined."
          />
          <KpiCard
            label="SLA Compliance"
            value={selected.kpis.sla}
            caption="Resolved within agreed time."
          />
          <KpiCard
            label="Avg Response Time"
            value={selected.kpis.avgResponse}
            caption="Time to first update."
          />
        </section>

        <section className="reportGrid">
          <article className="repCard">
            <h2 className="repCardTitle">Summary Breakdown</h2>
            <p className="repCardSubtitle">
              Snapshot of how you handled tickets this month.
            </p>

            <div className="summaryGrid">
              {selected.summary.map((item) => (
                <div key={item.label} className="summaryItem">
                  <span className="summaryLabel">{item.label}</span>
                  <span className="summaryValue">{item.value}</span>
                </div>
              ))}
            </div>
          </article>

          <aside className="repCard">
            <h2 className="repCardTitle">Rating Components</h2>
            <p className="repCardSubtitle">
              How your overall score was calculated.
            </p>

            <div className="ratingList">
              {selected.ratingComponents.map((rc) => (
                <div key={rc.name} className="ratingRow">
                  <span className="ratingName">{rc.name}</span>
                  <div className="ratingBar">
                    <div
                      className="ratingBarFill"
                      style={{ width: `${rc.pct}%` }}
                    />
                  </div>
                  <span className="ratingScore">{rc.score.toFixed(1)}</span>
                </div>
              ))}
            </div>
          </aside>
        </section>

        <section className="tableWrapper">
          <h2 className="repCardTitle">Weekly Activity Overview</h2>
          <p className="repCardSubtitle">
            Distribution of tickets across the month.
          </p>

          <div className="weekTableWrap">
            <table className="weekTable">
              <thead>
                <tr>
                  <th>Week</th>
                  <th>Tickets Assigned</th>
                  <th>Resolved</th>
                  <th>SLA Compliance</th>
                  <th>Avg Response Time</th>
                  <th>Change vs Previous Week</th>
                </tr>
              </thead>
              <tbody>
                {selected.weekly.map((row) => (
                  <tr key={row.week}>
                    <td>{row.week}</td>
                    <td>{row.assigned}</td>
                    <td>{row.resolved}</td>
                    <td>{row.sla}</td>
                    <td>{row.avg}</td>
                    <td>
                      <span
                        className={
                          row.delta.type === "positive"
                            ? "deltaPositive"
                            : "deltaNeutral"
                        }
                      >
                        {row.delta.text}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <ul className="notesList">
            {selected.notes.map((n) => (
              <li key={n}>{n}</li>
            ))}
          </ul>
        </section>
      </div>
    </Layout>
  );
}
