import Layout from "../../components/Layout";

export default function AutoGeneratedReports() {
  return (
    <Layout role="employee">
      <h2>Reports</h2>
      <p>Paste Reports UI here.</p>
    </Layout>
  );
}
