import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { pdf } from "@react-pdf/renderer";
import EmployeeReportPDF from "./EmployeeReportPDF";
import Layout from "../../components/Layout";
import PillSelect from "../../components/common/PillSelect";
import PageHeader from "../../components/common/PageHeader";
import KpiCard from "../../components/common/KpiCard";
import "./AutoGeneratedReports.css";

function monthKeyToReportId(monthKey) {
  if (!monthKey || typeof monthKey !== "string") return "";
  const match = monthKey.match(/^(\d{4})-(\d{2})$/);
  if (!match) return "";

  const year = match[1];
  const mm = match[2];

  const map = {
    "01": "jan",
    "02": "feb",
    "03": "mar",
    "04": "apr",
    "05": "may",
    "06": "jun",
    "07": "jul",
    "08": "aug",
    "09": "sep",
    "10": "oct",
    "11": "nov",
    "12": "dec",
  };

  const abbr = map[mm];
  return abbr ? `${abbr}-${year}` : "";
}

export default function AutoGeneratedReports() {
  const [searchParams] = useSearchParams();

  const reports = useMemo(
    () => [
      {
        id: "oct-2025",
        month: "October 2025",
        subtitle:
          "Auto-generated summary of your complaints, SLA performance, and activity for this month.",
        kpis: { rating: "92 / 100", resolved: 48, sla: "91%", avgResponse: "38 mins" },
        summary: [
          { label: "Total Tickets Assigned", value: 56 },
          { label: "Resolved Tickets", value: 48 },
          { label: "Pending / In Progress", value: 6 },
          { label: "Overdue Tickets", value: 2 },
          { label: "Critical & High Priority", value: 21 },
          { label: "Low & Medium Priority", value: 35 },
          { label: "First Contact Resolution", value: "67%" },
          { label: "Customer Follow-ups Needed", value: "16%" },
        ],
        ratingComponents: [
          { name: "Resolution Speed", score: 8.8, pct: 88 },
          { name: "Response Time", score: 9.0, pct: 90 },
          { name: "SLA Compliance", score: 9.2, pct: 92 },
          { name: "Escalations", score: 7.0, pct: 70 },
          { name: "Reopen Rate", score: 8.2, pct: 82 },
        ],
        weekly: [
          { week: "Week 1", assigned: 13, resolved: 10, sla: "88%", avg: "42 mins", delta: { type: "neutral", text: "Baseline" } },
          { week: "Week 2", assigned: 14, resolved: 12, sla: "90%", avg: "40 mins", delta: { type: "positive", text: "+2 resolved" } },
          { week: "Week 3", assigned: 16, resolved: 14, sla: "93%", avg: "37 mins", delta: { type: "positive", text: "+3 resolved" } },
          { week: "Week 4", assigned: 13, resolved: 12, sla: "92%", avg: "35 mins", delta: { type: "positive", text: "Stable" } },
        ],
        notes: [
          "Strong improvement in Week 3 after focusing on critical tickets first.",
          "Overdue tickets mostly linked to external vendor delays.",
          "Maintaining response time under 40 minutes keeps your rating above 90.",
        ],
      },
      {
        id: "sep-2025",
        month: "September 2025",
        subtitle:
          "Auto-generated summary of your complaints, SLA performance, and activity for this month.",
        kpis: { rating: "89 / 100", resolved: 44, sla: "88%", avgResponse: "44 mins" },
        summary: [
          { label: "Total Tickets Assigned", value: 52 },
          { label: "Resolved Tickets", value: 44 },
          { label: "Pending / In Progress", value: 7 },
          { label: "Overdue Tickets", value: 1 },
          { label: "Critical & High Priority", value: 18 },
          { label: "Low & Medium Priority", value: 34 },
          { label: "First Contact Resolution", value: "63%" },
          { label: "Customer Follow-ups Needed", value: "19%" },
        ],
        ratingComponents: [
          { name: "Resolution Speed", score: 8.4, pct: 84 },
          { name: "Response Time", score: 8.6, pct: 86 },
          { name: "SLA Compliance", score: 8.8, pct: 88 },
          { name: "Escalations", score: 7.3, pct: 73 },
          { name: "Reopen Rate", score: 8.1, pct: 81 },
        ],
        weekly: [
          { week: "Week 1", assigned: 12, resolved: 10, sla: "86%", avg: "46 mins", delta: { type: "neutral", text: "Baseline" } },
          { week: "Week 2", assigned: 14, resolved: 12, sla: "87%", avg: "45 mins", delta: { type: "positive", text: "Improving" } },
          { week: "Week 3", assigned: 15, resolved: 12, sla: "88%", avg: "43 mins", delta: { type: "positive", text: "Stable" } },
          { week: "Week 4", assigned: 11, resolved: 10, sla: "90%", avg: "42 mins", delta: { type: "positive", text: "Best week" } },
        ],
        notes: [
          "SLA improved toward the end of the month.",
          "Response time was slightly above target in early weeks.",
          "Try batching follow-ups to reduce delays.",
        ],
      },
      {
        id: "aug-2025",
        month: "August 2025",
        subtitle:
          "Auto-generated summary of your complaints, SLA performance, and activity for this month.",
        kpis: { rating: "87 / 100", resolved: 41, sla: "86%", avgResponse: "47 mins" },
        summary: [
          { label: "Total Tickets Assigned", value: 49 },
          { label: "Resolved Tickets", value: 41 },
          { label: "Pending / In Progress", value: 7 },
          { label: "Overdue Tickets", value: 1 },
          { label: "Critical & High Priority", value: 16 },
          { label: "Low & Medium Priority", value: 33 },
          { label: "First Contact Resolution", value: "61%" },
          { label: "Customer Follow-ups Needed", value: "20%" },
        ],
        ratingComponents: [
          { name: "Resolution Speed", score: 8.2, pct: 82 },
          { name: "Response Time", score: 8.3, pct: 83 },
          { name: "SLA Compliance", score: 8.6, pct: 86 },
          { name: "Escalations", score: 7.1, pct: 71 },
          { name: "Reopen Rate", score: 7.8, pct: 78 },
        ],
        weekly: [
          { week: "Week 1", assigned: 12, resolved: 9, sla: "84%", avg: "49 mins", delta: { type: "neutral", text: "Baseline" } },
          { week: "Week 2", assigned: 13, resolved: 11, sla: "86%", avg: "47 mins", delta: { type: "positive", text: "Improving" } },
          { week: "Week 3", assigned: 12, resolved: 10, sla: "87%", avg: "46 mins", delta: { type: "positive", text: "Stable" } },
          { week: "Week 4", assigned: 12, resolved: 11, sla: "88%", avg: "45 mins", delta: { type: "positive", text: "Best week" } },
        ],
        notes: [
          "SLA dipped early in the month due to backlog.",
          "Response time improved after mid-month prioritization.",
          "Keep focusing on first-contact resolution to raise the score.",
        ],
      },
      {
        id: "jul-2025",
        month: "July 2025",
        subtitle:
          "Auto-generated summary of your complaints, SLA performance, and activity for this month.",
        kpis: { rating: "85 / 100", resolved: 39, sla: "84%", avgResponse: "52 mins" },
        summary: [
          { label: "Total Tickets Assigned", value: 47 },
          { label: "Resolved Tickets", value: 39 },
          { label: "Pending / In Progress", value: 7 },
          { label: "Overdue Tickets", value: 1 },
          { label: "Critical & High Priority", value: 15 },
          { label: "Low & Medium Priority", value: 32 },
          { label: "First Contact Resolution", value: "58%" },
          { label: "Customer Follow-ups Needed", value: "22%" },
        ],
        ratingComponents: [
          { name: "Resolution Speed", score: 8.0, pct: 80 },
          { name: "Response Time", score: 8.1, pct: 81 },
          { name: "SLA Compliance", score: 8.4, pct: 84 },
          { name: "Escalations", score: 6.9, pct: 69 },
          { name: "Reopen Rate", score: 7.6, pct: 76 },
        ],
        weekly: [
          { week: "Week 1", assigned: 11, resolved: 8, sla: "82%", avg: "55 mins", delta: { type: "neutral", text: "Baseline" } },
          { week: "Week 2", assigned: 12, resolved: 10, sla: "83%", avg: "53 mins", delta: { type: "positive", text: "Improving" } },
          { week: "Week 3", assigned: 12, resolved: 10, sla: "85%", avg: "51 mins", delta: { type: "positive", text: "Stable" } },
          { week: "Week 4", assigned: 12, resolved: 11, sla: "86%", avg: "49 mins", delta: { type: "positive", text: "Best week" } },
        ],
        notes: [
          "Backlog was higher in Week 1, impacting response time.",
          "SLA increased gradually after Week 2.",
          "Reducing escalations will improve your overall rating.",
        ],
      },
      {
        id: "jun-2025",
        month: "June 2025",
        subtitle:
          "Auto-generated summary of your complaints, SLA performance, and activity for this month.",
        kpis: { rating: "83 / 100", resolved: 36, sla: "82%", avgResponse: "58 mins" },
        summary: [
          { label: "Total Tickets Assigned", value: 45 },
          { label: "Resolved Tickets", value: 36 },
          { label: "Pending / In Progress", value: 8 },
          { label: "Overdue Tickets", value: 1 },
          { label: "Critical & High Priority", value: 14 },
          { label: "Low & Medium Priority", value: 31 },
          { label: "First Contact Resolution", value: "55%" },
          { label: "Customer Follow-ups Needed", value: "24%" },
        ],
        ratingComponents: [
          { name: "Resolution Speed", score: 7.8, pct: 78 },
          { name: "Response Time", score: 7.9, pct: 79 },
          { name: "SLA Compliance", score: 8.2, pct: 82 },
          { name: "Escalations", score: 6.7, pct: 67 },
          { name: "Reopen Rate", score: 7.4, pct: 74 },
        ],
        weekly: [
          { week: "Week 1", assigned: 11, resolved: 8, sla: "80%", avg: "60 mins", delta: { type: "neutral", text: "Baseline" } },
          { week: "Week 2", assigned: 12, resolved: 9, sla: "81%", avg: "59 mins", delta: { type: "positive", text: "Improving" } },
          { week: "Week 3", assigned: 11, resolved: 9, sla: "83%", avg: "57 mins", delta: { type: "positive", text: "Stable" } },
          { week: "Week 4", assigned: 11, resolved: 10, sla: "84%", avg: "56 mins", delta: { type: "positive", text: "Best week" } },
        ],
        notes: [
          "High follow-ups contributed to longer resolution cycles.",
          "SLA improved slightly by the end of the month.",
          "Focus on faster first response to lift the rating.",
        ],
      },
    ],
    []
  );

  const reportFromUrlRaw = searchParams.get("report");

  const normalizedReportParam = (() => {
    if (!reportFromUrlRaw) return null;

    // If it's already a valid report id, keep it
    if (reports.some((r) => r.id === reportFromUrlRaw)) return reportFromUrlRaw;

    // If it's "YYYY-MM", convert to "mon-YYYY"
    const converted = monthKeyToReportId(reportFromUrlRaw);
    if (converted && reports.some((r) => r.id === converted)) return converted;

    return null;
  })();

  const initialId = normalizedReportParam ?? reports[0].id;

  const [selectedId, setSelectedId] = useState(initialId);

  useEffect(() => {
    if (normalizedReportParam) {
      setSelectedId(normalizedReportParam);
    }
  }, [normalizedReportParam]);

  const selected = reports.find((r) => r.id === selectedId) || reports[0];

  const handleDownload = async () => {
    const name = "Mayed Sharaf";
    const blob = await pdf(
      <EmployeeReportPDF
        report={selected}
        employeeName={name}
        employeeId="EMP123"
        downloadDate={new Date()}
      />
    ).toBlob();

    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${name}-${selected.month}-Report.pdf`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };

  return (
    <Layout role="employee">
      <div className="empReportsPage">
        <PageHeader
          title={`Monthly Performance Report – ${selected.month}`}
          subtitle={selected.subtitle}
          actions={
            <>
              <PillSelect
                value={selectedId}
                onChange={setSelectedId}
                ariaLabel="Select month report"
                options={reports.map((r) => ({ value: r.id, label: r.month }))}
              />
              <button className="downloadBtn" onClick={handleDownload}>
                Download PDF
              </button>
            </>
          }
        />

        <section className="kpiRow">
          <KpiCard
            label="Overall Rating"
            value={selected.kpis.rating}
            caption="Based on closure rate & SLA."
          />
          <KpiCard
            label="Complaints Resolved"
            value={selected.kpis.resolved}
            caption="All priorities combined."
          />
          <KpiCard
            label="SLA Compliance"
            value={selected.kpis.sla}
            caption="Resolved within agreed time."
          />
          <KpiCard
            label="Avg Response Time"
            value={selected.kpis.avgResponse}
            caption="Time to first update."
          />
        </section>

        <section className="reportGrid">
          <article className="repCard">
            <h2 className="repCardTitle">Summary Breakdown</h2>
            <p className="repCardSubtitle">
              Snapshot of how you handled tickets this month.
            </p>

            <div className="summaryGrid">
              {selected.summary.map((item) => (
                <div key={item.label} className="summaryItem">
                  <span className="summaryLabel">{item.label}</span>
                  <span className="summaryValue">{item.value}</span>
                </div>
              ))}
            </div>
          </article>

          <aside className="repCard">
            <h2 className="repCardTitle">Rating Components</h2>
            <p className="repCardSubtitle">
              How your overall score was calculated.
            </p>

            <div className="ratingList">
              {selected.ratingComponents.map((rc) => (
                <div key={rc.name} className="ratingRow">
                  <span className="ratingName">{rc.name}</span>
                  <div className="ratingBar">
                    <div
                      className="ratingBarFill"
                      style={{ width: `${rc.pct}%` }}
                    />
                  </div>
                  <span className="ratingScore">{rc.score.toFixed(1)}</span>
                </div>
              ))}
            </div>
          </aside>
        </section>

        <section className="tableWrapper">
          <h2 className="repCardTitle">Weekly Activity Overview</h2>
          <p className="repCardSubtitle">
            Distribution of tickets across the month.
          </p>

          <div className="weekTableWrap">
            <table className="weekTable">
              <thead>
                <tr>
                  <th>Week</th>
                  <th>Tickets Assigned</th>
                  <th>Resolved</th>
                  <th>SLA Compliance</th>
                  <th>Avg Response Time</th>
                  <th>Change vs Previous Week</th>
                </tr>
              </thead>
              <tbody>
                {selected.weekly.map((row) => (
                  <tr key={row.week}>
                    <td>{row.week}</td>
                    <td>{row.assigned}</td>
                    <td>{row.resolved}</td>
                    <td>{row.sla}</td>
                    <td>{row.avg}</td>
                    <td>
                      <span
                        className={
                          row.delta.type === "positive"
                            ? "deltaPositive"
                            : "deltaNeutral"
                        }
                      >
                        {row.delta.text}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <ul className="notesList">
            {selected.notes.map((n) => (
              <li key={n}>{n}</li>
            ))}
          </ul>
        </section>
      </div>
    </Layout>
  );
}
