"""
Phase 3 — Classifier Evaluation Against LLM-Labeled Test Set
=============================================================
Reads a test CSV that has ground truth labels generated by an LLM (e.g. Claude),
runs the Phase 2 DeBERTa classifier on the texts, and compares predictions
against ground truth across all four labels.

Expected test CSV columns:
    ticket_type, text, issue_severity, issue_urgency, safety_concern, business_impact

Only complaint rows are evaluated (inquiries have no labels).

Metrics reported per label:
    - Accuracy
    - F1 score (macro)
    - Per-class precision & recall
    - Confusion matrix

Requirements:
    pip install -r data/synthesizerv7/requirements.txt

Usage:
    python phase3_evaluate.py --test test.csv

    # Save full results with predictions alongside ground truth
    python phase3_evaluate.py --test test.csv --output output/predictions.csv
"""

import argparse
from pathlib import Path

import pandas as pd
import torch
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    f1_score,
    precision_recall_fscore_support,
)
from tqdm import tqdm
from transformers import pipeline

# Reuse the same LABEL_CONFIGS from Phase 2
LABEL_CONFIGS = {
    "issue_severity": {
        "low": [
            "the technical problem described is minor and does not affect core facility systems",
            "this is a small defect or inconvenience within the tenant space",
            "the issue is localized and does not impact building infrastructure",
        ],
        "medium": [
            "the problem affects part of the facility but not the entire operation",
            "this issue impacts important systems but does not cause full service failure",
            "the fault disrupts some building functions but operations can continue",
        ],
        "high": [
            "the issue represents a critical failure of core facility infrastructure",
            "this problem involves major system breakdown affecting the facility",
            "the complaint describes a severe technical failure within the building",
        ],
    },
    "issue_urgency": {
        "low": [
            "this issue can be scheduled for routine maintenance without immediate action",
            "the problem does not require urgent intervention",
            "the situation can be resolved in normal service timelines",
        ],
        "medium": [
            "this issue should be addressed soon to prevent escalation",
            "the problem requires timely action but is not an emergency",
            "delayed resolution may cause additional complications",
        ],
        "high": [
            "this issue requires immediate intervention",
            "the problem demands urgent action to prevent serious consequences",
            "failure to act quickly could cause significant damage or escalation",
        ],
    },
    "safety_concern": {
        True: [
            "the issue involves a risk to human health or physical safety",
            "this complaint describes a hazardous situation for tenants or staff",
            "the problem poses potential injury or health danger within the facility",
        ],
        False: [
            "the issue does not involve any risk to human safety",
            "this complaint concerns operational matters without safety hazards",
            "there is no indication of health or physical danger in this issue",
        ],
    },
    "business_impact": {
        "low": [
            "the issue causes minimal disruption to tenant business operations",
            "business activities can continue normally despite this problem",
            "the operational impact on the tenant is negligible",
        ],
        "medium": [
            "the issue is causing noticeable disruption to tenant operations",
            "business productivity is partially affected by this problem",
            "the complaint indicates moderate operational disturbance",
        ],
        "high": [
            "the issue is significantly disrupting tenant business operations",
            "this problem is preventing normal business continuity",
            "the complaint describes major operational or financial impact",
        ],
    },
}

BASE_DIR = Path(__file__).resolve().parent
CLASSIFIER_MODEL_DIR = BASE_DIR / "models" / "classifier" / "deberta-v3-base-mnli-fever-anli"
REMOTE_MODEL_NAME = "MoritzLaurer/DeBERTa-v3-base-mnli-fever-anli"
LABEL_COLUMNS = ["issue_severity", "issue_urgency", "safety_concern", "business_impact"]
MODEL_NAME = str(CLASSIFIER_MODEL_DIR) if CLASSIFIER_MODEL_DIR.exists() else REMOTE_MODEL_NAME
DEFAULT_OUTPUT_PATH = "output/predictions.csv"


# ─────────────────────────────────────────────
# CLASSIFIER (same logic as Phase 2)
# ─────────────────────────────────────────────

def load_classifier(
    model_name: str = MODEL_NAME,
    quantization: str = "auto",
    force_cpu: bool = False,
):
    device = -1 if force_cpu else (0 if torch.cuda.is_available() else -1)
    device_label = "GPU" if device == 0 else "CPU"
    print(f"\nLoading classifier on {device_label}...")

    use_8bit = (not force_cpu) and (
        quantization == "8bit" or (quantization == "auto" and torch.cuda.is_available())
    )
    pipe_kwargs = {
        "task": "zero-shot-classification",
        "model": model_name,
    }

    if use_8bit:
        try:
            from transformers import BitsAndBytesConfig

            pipe_kwargs["model_kwargs"] = {
                "quantization_config": BitsAndBytesConfig(load_in_8bit=True),
            }
            print("Using 8-bit quantization (bitsandbytes)")
        except Exception as exc:
            print(f"[WARN] Could not enable 8-bit quantization: {exc}")
            print("[WARN] Falling back to standard precision load")
            pipe_kwargs["device"] = device
    else:
        pipe_kwargs["device"] = device

    try:
        clf = pipeline(**pipe_kwargs)
    except ValueError as exc:
        if "load_in_8bit_fp32_cpu_offload" in str(exc):
            print("[WARN] VRAM insufficient for pure 8-bit placement; retrying with CPU offload")
            try:
                from transformers import BitsAndBytesConfig

                offload_kwargs = {
                    "task": "zero-shot-classification",
                    "model": model_name,
                    "model_kwargs": {
                        "quantization_config": BitsAndBytesConfig(
                            load_in_8bit=True,
                            llm_int8_enable_fp32_cpu_offload=True,
                        ),
                        "device_map": "auto",
                    },
                }
                clf = pipeline(**offload_kwargs)
            except Exception as offload_exc:
                print(f"[WARN] 8-bit offload retry failed: {offload_exc}")
                print("[WARN] Falling back to compatibility loader")
                fallback_kwargs = {
                    "task": "zero-shot-classification",
                    "model": model_name,
                    "device": device,
                }
                clf = pipeline(**fallback_kwargs)
        else:
            raise
    except TypeError as exc:
        print(f"[WARN] Pipeline args not accepted ({exc}); retrying with compatibility fallback")
        fallback_kwargs = {
            "task": "zero-shot-classification",
            "model": model_name,
            "device": device,
        }
        clf = pipeline(**fallback_kwargs)
    print("Classifier ready")
    return clf


def classify_ticket(classifier, text: str) -> dict:
    results = {}
    for label_name, class_hypotheses in LABEL_CONFIGS.items():
        all_hypotheses = [
            hypothesis
            for hypotheses in class_hypotheses.values()
            for hypothesis in hypotheses
        ]
        output = classifier(text, candidate_labels=all_hypotheses, multi_label=True)
        score_map = dict(zip(output["labels"], output["scores"]))
        class_scores = {
            cls: sum(score_map[h] for h in hyps) / len(hyps)
            for cls, hyps in class_hypotheses.items()
        }
        results[label_name] = max(class_scores, key=class_scores.get)
    return results


# ─────────────────────────────────────────────
# NORMALISATION
# Handles casing/type differences between
# ground truth and predictions
# ─────────────────────────────────────────────

def normalise_safety(val):
    """Converts various truth representations to Python bool."""
    if isinstance(val, bool):
        return val
    if isinstance(val, str):
        return val.strip().lower() in ("true", "1", "yes")
    return bool(val)


def normalise_label(col: str, val):
    if col == "safety_concern":
        return normalise_safety(val)
    return str(val).strip().lower()


def validate_test_frame(df: pd.DataFrame) -> None:
    missing = {"ticket_type", "text"} - set(df.columns)
    if missing:
        raise ValueError(f"Test CSV missing required columns: {missing}")

    missing_labels = [c for c in LABEL_COLUMNS if c not in df.columns]
    if missing_labels:
        raise ValueError(f"Test CSV missing label columns: {missing_labels}")


def normalise_truth_columns(df: pd.DataFrame) -> None:
    for col in LABEL_COLUMNS:
        df[f"{col}_truth"] = df[col].apply(lambda value: normalise_label(col, value))


def predict_all(
    classifier,
    texts: list[str],
    model_name: str,
    quantization: str,
) -> pd.DataFrame:
    predictions = []
    active_classifier = classifier
    cpu_fallback_classifier = None
    for text in tqdm(texts, total=len(texts), desc="Classifying"):
        try:
            pred = classify_ticket(active_classifier, text)
        except torch.OutOfMemoryError:
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
            print("  [WARN] CUDA OOM during Phase 3 evaluation")
            if cpu_fallback_classifier is None:
                print("  [WARN] Loading CPU fallback classifier for remaining rows")
                cpu_fallback_classifier = load_classifier(
                    model_name=model_name,
                    quantization="none",
                    force_cpu=True,
                )
            active_classifier = cpu_fallback_classifier
            pred = classify_ticket(active_classifier, text)
        predictions.append({col: normalise_label(col, value) for col, value in pred.items()})
    return pd.DataFrame(predictions)


# ─────────────────────────────────────────────
# REPORTING
# ─────────────────────────────────────────────

def print_separator(char="=", width=60):
    print(char * width)


def report_label(col: str, y_true: list, y_pred: list):
    classes = sorted(set(y_true) | set(y_pred), key=str)

    acc     = accuracy_score(y_true, y_pred)
    f1_mac  = f1_score(y_true, y_pred, average="macro", zero_division=0)
    prec, rec, f1_per, support = precision_recall_fscore_support(
        y_true, y_pred, labels=classes, zero_division=0
    )
    cm = confusion_matrix(y_true, y_pred, labels=classes)

    print_separator()
    print(f"  {col.upper().replace('_', ' ')}")
    print_separator()
    print(f"  Accuracy : {acc:.3f}   |   F1 (macro) : {f1_mac:.3f}")
    print()

    # Per-class table
    col_w = max(len(str(c)) for c in classes) + 2
    header = f"  {'Class':<{col_w}}  {'Precision':>10}  {'Recall':>10}  {'F1':>8}  {'Support':>8}"
    print(header)
    print("  " + "-" * (col_w + 42))
    for i, cls in enumerate(classes):
        print(f"  {str(cls):<{col_w}}  {prec[i]:>10.3f}  {rec[i]:>10.3f}  {f1_per[i]:>8.3f}  {support[i]:>8}")

    # Confusion matrix
    print()
    print("  Confusion Matrix (rows=actual, cols=predicted):")
    cls_labels = [str(c) for c in classes]
    pad = max(len(s) for s in cls_labels) + 1
    header_row = " " * (pad + 4) + "  ".join(f"{s:>{pad}}" for s in cls_labels)
    print("  " + header_row)
    for i, cls in enumerate(classes):
        row = "  ".join(f"{cm[i][j]:>{pad}}" for j in range(len(classes)))
        print(f"  {str(cls):>{pad}} |  {row}")
    print()


def print_summary(results: dict[str, dict[str, float]]):
    print_separator("=")
    print("  SUMMARY")
    print_separator("=")
    print(f"  {'Label':<20}  {'Accuracy':>10}  {'F1 (macro)':>12}")
    print("  " + "-" * 46)
    for col, metrics in results.items():
        print(f"  {col:<20}  {metrics['accuracy']:>10.3f}  {metrics['f1_macro']:>12.3f}")
    print_separator("=")
    print()


def evaluate_labels(df: pd.DataFrame) -> dict[str, dict[str, float]]:
    summary_results: dict[str, dict[str, float]] = {}
    for col in LABEL_COLUMNS:
        y_true = df[f"{col}_truth"].tolist()
        y_pred = df[f"{col}_pred"].tolist()
        report_label(col, y_true, y_pred)
        summary_results[col] = {
            "accuracy": accuracy_score(y_true, y_pred),
            "f1_macro": f1_score(y_true, y_pred, average="macro", zero_division=0),
        }
    return summary_results


def maybe_save_output(df: pd.DataFrame, output_path: str | None) -> None:
    if not output_path:
        return
    out_cols = ["text"] + [f"{c}_truth" for c in LABEL_COLUMNS] + [f"{c}_pred" for c in LABEL_COLUMNS]
    out_df = df[[c for c in out_cols if c in df.columns]]
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    out_df.to_csv(output_path, index=False)
    print(f"Predictions saved to: {output_path}")


# ─────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Phase 3: Evaluate DeBERTa classifier against LLM-labeled test set")
    parser.add_argument("--test",    required=True,                        help="Path to test CSV with ground truth labels")
    parser.add_argument("--output",  default=DEFAULT_OUTPUT_PATH,          help="Path to save predictions + ground truth CSV")
    parser.add_argument("--model",   default=MODEL_NAME)
    parser.add_argument(
        "--quantization",
        choices=["auto", "none", "8bit"],
        default="auto",
        help="Model quantization mode (default: auto; uses 8bit on CUDA)",
    )
    args = parser.parse_args()

    # ── Load test data ──
    print(f"\nLoading test data: {args.test}")
    df = pd.read_csv(args.test)
    validate_test_frame(df)

    # Complaints only
    df = df[df["ticket_type"] == "complaint"].copy().reset_index(drop=True)
    print(f"Evaluating {len(df)} complaint rows")

    if len(df) == 0:
        raise ValueError("No complaint rows found in test CSV")

    # Normalise ground truth
    normalise_truth_columns(df)

    # ── Load classifier ──
    classifier = load_classifier(args.model, args.quantization)

    # ── Run predictions ──
    pred_df = predict_all(
        classifier,
        df["text"].tolist(),
        model_name=args.model,
        quantization=args.quantization,
    )
    for col in LABEL_COLUMNS:
        df[f"{col}_pred"] = pred_df[col]

    # ── Report ──
    print("\n")
    summary_results = evaluate_labels(df)

    print_summary(summary_results)

    # ── Optional output CSV ──
    maybe_save_output(df, args.output)


if __name__ == "__main__":
    main()
