import { BrowserRouter, Routes, Route, Navigate } from "react-router-dom";
import { Suspense, lazy } from "react";

import ProtectedRoute from "./auth/ProtectedRoute";

const Login = lazy(() => import("./pages/Login"));
const ForgotPassword = lazy(() => import("./pages/ForgotPassword"));
const SkipViewSelector = lazy(() => import("./pages/SkipViewSelector"));

const CustomerLanding = lazy(() => import("./pages/customer/CustomerLanding"));
const CustomerNotifications = lazy(() =>
  import("./pages/customer/CustomerNotifications")
);
const CustomerHistory = lazy(() => import("./pages/customer/CustomerHistory"));
const CustomerFillForm = lazy(() => import("./pages/customer/CustomerFillForm"));
const CustomerTicketDetails = lazy(() =>
  import("./pages/customer/CustomerTicketDetails")
);
const CustomerSettings = lazy(() => import("./pages/customer/CustomerSettings"));
const CustomerAuthPage = lazy(() =>
  import("./pages/customer/CustomerAuthPage")
);





const EmployeeNotifications = lazy(() =>
  import("./pages/employee/EmployeeNotifications")
);
const AutoGeneratedReports = lazy(() =>
  import("./pages/employee/AutoGeneratedReports")
);
const ComplaintDetails = lazy(() => import("./pages/employee/ComplaintDetails"));
const EmployeeDashboard = lazy(() => import("./pages/employee/EmployeeDashboard"));
const EmployeeViewAllComplaints = lazy(() =>
  import("./pages/employee/EmployeeViewAllComplaints")
);

const ManagerNotifications = lazy(() =>
  import("./pages/manager/ManagerNotifications")
);
const Approvals = lazy(() => import("./pages/manager/Approvals"));
const ComplaintTrends = lazy(() => import("./pages/manager/ComplaintTrends"));
const ManagerDashboard = lazy(() => import("./pages/manager/ManagerDashboard"));
const ManagerViewAllComplaints = lazy(() =>
  import("./pages/manager/ManagerViewAllComplaints")
);
const ManagerComplaintDetails = lazy(() =>
  import("./pages/manager/ManagerComplaintDetails")
);
const ViewEmployees = lazy(() => import("./pages/manager/ManagerViewEmployees"));

const OperatorNotifications = lazy(() =>
  import("./pages/operator/OperatorNotifications")
);
const ChatbotAnalysis = lazy(() => import("./pages/operator/ChatbotAnalysis"));
const ModelAnalysis = lazy(() => import("./pages/operator/ModelAnalysis"));
const OperatorDashboard = lazy(() => import("./pages/operator/OperatorDashboard"));

export default function App() {
  return (
    <BrowserRouter>
      <Suspense
        fallback={
          <div style={{ padding: 20, fontFamily: "system-ui" }}>Loading…</div>
        }
      >
        <Routes>
          
          <Route path="/" element={<Login />} />
          <Route path="/skip" element={<SkipViewSelector />} />
          <Route path="/forgot-password" element={<ForgotPassword />} />

          <Route path="/" element={<Login />} />
          <Route path="/forgot-password" element={<ForgotPassword />} />
          <Route path="/verify" element={<CustomerAuthPage />} />

          
          <Route
            path="/customer"
            element={
              <ProtectedRoute role="customer">
                <CustomerLanding />
              </ProtectedRoute>
            }
          />

          
          <Route
            path="/customer/dashboard"
            element={<Navigate to="/customer" replace />}
          />

          
          <Route
            path="/customer/notifications"
            element={
              <ProtectedRoute role="customer">
                <CustomerNotifications />
              </ProtectedRoute>
            }
          />
          <Route
            path="/customer/mytickets"
            element={
              <ProtectedRoute role="customer">
                <CustomerHistory />
              </ProtectedRoute>
            }
          />
          <Route
            path="/customer/fill-form"
            element={
              <ProtectedRoute role="customer">
                <CustomerFillForm />
              </ProtectedRoute>
            }
          />
          <Route
            path="/customer/ticket/:id"
            element={
              <ProtectedRoute role="customer">
                <CustomerTicketDetails />
              </ProtectedRoute>
            }
          />

          <Route
            path="/customer/settings"
            element={
              <ProtectedRoute role="customer">
                <CustomerSettings />
              </ProtectedRoute>
            }
          />

          
          <Route
            path="/employee"
            element={
              <ProtectedRoute role="employee">
                <EmployeeDashboard />
              </ProtectedRoute>
            }
          />
          <Route
            path="/employee/complaints"
            element={
              <ProtectedRoute role="employee">
                <EmployeeViewAllComplaints />
              </ProtectedRoute>
            }
          />
          <Route
            path="/employee/details/:id"
            element={
              <ProtectedRoute role="employee">
                <ComplaintDetails />
              </ProtectedRoute>
            }
          />
          <Route
            path="/employee/reports"
            element={
              <ProtectedRoute role="employee">
                <AutoGeneratedReports />
              </ProtectedRoute>
            }
          />
          <Route
            path="/employee/notifications"
            element={
              <ProtectedRoute role="employee">
                <EmployeeNotifications />
              </ProtectedRoute>
            }
          />

          
          <Route
            path="/manager"
            element={
              <ProtectedRoute role="manager">
                <ManagerDashboard />
              </ProtectedRoute>
            }
          />
          <Route
            path="/manager/complaints"
            element={
              <ProtectedRoute role="manager">
                <ManagerViewAllComplaints />
              </ProtectedRoute>
            }
          />
          <Route
            path="/manager/complaints/:id"
            element={
              <ProtectedRoute role="manager">
                <ManagerComplaintDetails />
              </ProtectedRoute>
            }
          />
          <Route
            path="/manager/employees"
            element={
              <ProtectedRoute role="manager">
                <ViewEmployees />
              </ProtectedRoute>
            }
          />
          <Route
            path="/manager/approvals"
            element={
              <ProtectedRoute role="manager">
                <Approvals />
              </ProtectedRoute>
            }
          />
          <Route
            path="/manager/trends"
            element={
              <ProtectedRoute role="manager">
                <ComplaintTrends />
              </ProtectedRoute>
            }
          />
          <Route
            path="/manager/notifications"
            element={
              <ProtectedRoute role="manager">
                <ManagerNotifications />
              </ProtectedRoute>
            }
          />

          
          <Route
            path="/operator"
            element={
              <ProtectedRoute role="operator">
                <OperatorDashboard />
              </ProtectedRoute>
            }
          />
          <Route
            path="/operator/model-analysis"
            element={
              <ProtectedRoute role="operator">
                <ModelAnalysis />
              </ProtectedRoute>
            }
          />
          <Route
            path="/operator/chatbot-analysis"
            element={
              <ProtectedRoute role="operator">
                <ChatbotAnalysis />
              </ProtectedRoute>
            }
          />
          <Route
            path="/operator/notifications"
            element={
              <ProtectedRoute role="operator">
                <OperatorNotifications />
              </ProtectedRoute>
            }
          />
        </Routes>
      </Suspense>
    </BrowserRouter>
  );
}
