import { BrowserRouter, Routes, Route, Navigate } from "react-router-dom";
import { Suspense, lazy, useEffect } from "react";

import ProtectedRoute from "./auth/ProtectedRoute";

const PublicLanding = lazy(() => import("./pages/PublicLanding"));
const Login = lazy(() => import("./pages/Login"));
const ForgotPassword = lazy(() => import("./pages/ForgotPassword"));

const CustomerLanding = lazy(() => import("./pages/customer/CustomerLanding"));
const CustomerNotifications = lazy(() =>
  import("./pages/customer/CustomerNotifications")
);
const CustomerHistory = lazy(() => import("./pages/customer/CustomerHistory"));
const CustomerFillForm = lazy(() => import("./pages/customer/CustomerFillForm"));
const CustomerTicketDetails = lazy(() =>
  import("./pages/customer/CustomerTicketDetails")
);
const CustomerSettings = lazy(() => import("./pages/customer/CustomerSettings"));
const CustomerAuthPage = lazy(() => import("./pages/customer/CustomerAuthPage"));
const AboutUs = lazy(() => import("./pages/customer/AboutUs"));

const EmployeeNotifications = lazy(() =>
  import("./pages/employee/EmployeeNotifications")
);
const AutoGeneratedReports = lazy(() =>
  import("./pages/employee/AutoGeneratedReports")
);
const ComplaintDetails = lazy(() => import("./pages/employee/ComplaintDetails"));
const EmployeeDashboard = lazy(() => import("./pages/employee/EmployeeDashboard"));
const EmployeeViewAllComplaints = lazy(() =>
  import("./pages/employee/EmployeeViewAllComplaints")
);
const EmployeeSettings = lazy(() => import("./pages/employee/EmployeeSettings"));

const ManagerNotifications = lazy(() =>
  import("./pages/manager/ManagerNotifications")
);
const Approvals = lazy(() => import("./pages/manager/Approvals"));
const ComplaintTrends = lazy(() => import("./pages/manager/ComplaintTrends"));
const ManagerDashboard = lazy(() => import("./pages/manager/ManagerDashboard"));
const ManagerViewAllComplaints = lazy(() =>
  import("./pages/manager/ManagerViewAllComplaints")
);
const ManagerComplaintDetails = lazy(() =>
  import("./pages/manager/ManagerComplaintDetails")
);
const ApprovalRequestDetails = lazy(() =>
  import("./pages/manager/ApprovalRequestDetails")
);
const ViewEmployees = lazy(() => import("./pages/manager/ManagerViewEmployees"));
const ManagerSettings = lazy(() => import("./pages/manager/ManagerSettings"));

const OperatorNotifications = lazy(() =>
  import("./pages/operator/OperatorNotifications")
);
const QualityControl = lazy(() => import("./pages/operator/QualityControl"));
const ModelHealth = lazy(() => import("./pages/operator/ModelHealth"));
const OperatorDashboard = lazy(() => import("./pages/operator/OperatorDashboard"));
const UsersManagement = lazy(() => import("./pages/operator/UsersManagement"));
const OperatorSettings = lazy(() => import("./pages/operator/OperatorSettings"));
const TicketReviewDetail = lazy(() => import("./pages/operator/TicketReviewDetail"));

const isStaffHost = () => window.location.hostname.startsWith("staff.");

function RootGate() {
  // "/" entry behavior differs by host
  return isStaffHost() ? <Navigate to="/login" replace /> : <PublicLanding />;
}

function PublicOnly({ children }) {
  // block customer public pages on staff subdomain
  if (isStaffHost()) return <Navigate to="/login" replace />;
  return children;
}

export default function App() {
  useEffect(() => {
    document.title = "InnovaCX";

    const href = "/innovacx-favicon.svg?v=20260224b";
    const rels = ["icon", "shortcut icon"];

    rels.forEach((rel) => {
      let link = document.querySelector(`link[rel='${rel}']`);
      if (!link) {
        link = document.createElement("link");
        link.setAttribute("rel", rel);
        document.head.appendChild(link);
      }
      link.setAttribute("href", href);
      link.setAttribute("type", "image/svg+xml");
    });
  }, []);

  return (
    <BrowserRouter>
      <Suspense
        fallback={
          <div style={{ padding: 20, fontFamily: "system-ui" }}>Loading…</div>
        }
      >
        <Routes>
          {/* Root split */}
          <Route path="/" element={<RootGate />} />

          {/* Public customer-only pages */}
          <Route
            path="/about"
            element={
              <PublicOnly>
                <AboutUs />
              </PublicOnly>
            }
          />
          <Route
            path="/verify"
            element={
              <PublicOnly>
                <CustomerAuthPage />
              </PublicOnly>
            }
          />

          {/* Login should work on staff; you can still allow it on customer if you want */}
          <Route path="/login" element={<Login />} />
          <Route path="/forgot-password" element={<ForgotPassword />} />

          {/* Customer protected routes */}
          <Route
            path="/customer"
            element={
              <ProtectedRoute role="customer">
                <CustomerLanding />
              </ProtectedRoute>
            }
          />
          <Route
            path="/customer/dashboard"
            element={<Navigate to="/customer" replace />}
          />
          <Route
            path="/customer/notifications"
            element={
              <ProtectedRoute role="customer">
                <CustomerNotifications />
              </ProtectedRoute>
            }
          />
          <Route
            path="/customer/mytickets"
            element={
              <ProtectedRoute role="customer">
                <CustomerHistory />
              </ProtectedRoute>
            }
          />
          <Route
            path="/customer/fill-form"
            element={
              <ProtectedRoute role="customer">
                <CustomerFillForm />
              </ProtectedRoute>
            }
          />
          <Route
            path="/customer/ticket/:id"
            element={
              <ProtectedRoute role="customer">
                <CustomerTicketDetails />
              </ProtectedRoute>
            }
          />
          <Route
            path="/customer/settings"
            element={
              <ProtectedRoute role="customer">
                <CustomerSettings />
              </ProtectedRoute>
            }
          />
          <Route
            path="/customer/about"
            element={
              <ProtectedRoute role="customer">
                <AboutUs />
              </ProtectedRoute>
            }
          />

          {/* Employee */}
          <Route
            path="/employee"
            element={
              <ProtectedRoute role="employee">
                <EmployeeDashboard />
              </ProtectedRoute>
            }
          />
          <Route
            path="/employee/complaints"
            element={
              <ProtectedRoute role="employee">
                <EmployeeViewAllComplaints />
              </ProtectedRoute>
            }
          />
          <Route
            path="/employee/details/:id"
            element={
              <ProtectedRoute role="employee">
                <ComplaintDetails />
              </ProtectedRoute>
            }
          />
          <Route
            path="/employee/reports"
            element={
              <ProtectedRoute role="employee">
                <AutoGeneratedReports />
              </ProtectedRoute>
            }
          />
          <Route
            path="/employee/notifications"
            element={
              <ProtectedRoute role="employee">
                <EmployeeNotifications />
              </ProtectedRoute>
            }
          />
          <Route
            path="/employee/settings"
            element={
              <ProtectedRoute role="employee">
                <EmployeeSettings />
              </ProtectedRoute>
            }
          />

          {/* Manager */}
          <Route
            path="/manager"
            element={
              <ProtectedRoute role="manager">
                <ManagerDashboard />
              </ProtectedRoute>
            }
          />
          <Route
            path="/manager/complaints"
            element={
              <ProtectedRoute role="manager">
                <ManagerViewAllComplaints />
              </ProtectedRoute>
            }
          />
          <Route
            path="/manager/complaints/:id"
            element={
              <ProtectedRoute role="manager">
                <ManagerComplaintDetails />
              </ProtectedRoute>
            }
          />
          <Route
            path="/manager/employees"
            element={
              <ProtectedRoute role="manager">
                <ViewEmployees />
              </ProtectedRoute>
            }
          />
          <Route
            path="/manager/approvals"
            element={
              <ProtectedRoute role="manager">
                <Approvals />
              </ProtectedRoute>
            }
          />
          <Route
            path="/manager/approvals/:requestId"
            element={
              <ProtectedRoute role="manager">
                <ApprovalRequestDetails />
              </ProtectedRoute>
            }
          />
          <Route
            path="/manager/trends"
            element={
              <ProtectedRoute role="manager">
                <ComplaintTrends />
              </ProtectedRoute>
            }
          />
          <Route
            path="/manager/notifications"
            element={
              <ProtectedRoute role="manager">
                <ManagerNotifications />
              </ProtectedRoute>
            }
          />
          <Route
            path="/manager/settings"
            element={
              <ProtectedRoute role="manager">
                <ManagerSettings />
              </ProtectedRoute>
            }
          />

          {/* Operator */}
          <Route
            path="/operator"
            element={
              <ProtectedRoute role="operator">
                <OperatorDashboard />
              </ProtectedRoute>
            }
          />
          <Route
            path="/operator/model-health"
            element={
              <ProtectedRoute role="operator">
                <ModelHealth />
              </ProtectedRoute>
            }
          />
          <Route
            path="/operator/quality-control"
            element={
              <ProtectedRoute role="operator">
                <QualityControl />
              </ProtectedRoute>
            }
          />
          <Route
            path="/operator/quality-control/review/:ticketId"
            element={
              <ProtectedRoute role="operator">
                <TicketReviewDetail />
              </ProtectedRoute>
            }
          />
          <Route
            path="/operator/users"
            element={
              <ProtectedRoute role="operator">
                <UsersManagement />
              </ProtectedRoute>
            }
          />
          <Route
            path="/operator/notifications"
            element={
              <ProtectedRoute role="operator">
                <OperatorNotifications />
              </ProtectedRoute>
            }
          />
          <Route
            path="/operator/settings"
            element={
              <ProtectedRoute role="operator">
                <OperatorSettings />
              </ProtectedRoute>
            }
          />

          {/* Fallback */}
          <Route path="*" element={<Navigate to="/" replace />} />
        </Routes>
      </Suspense>
    </BrowserRouter>
  );
}