import { BrowserRouter, Routes, Route } from "react-router-dom";

import Login from "./pages/Login";

// customer view:
import Chatbot from "./pages/customer/Chatbot";

// employee view: 
import AutoGeneratedReports from "./pages/employee/AutoGeneratedReports";
import ComplaintDetails from "./pages/employee/ComplaintDetails";
import EmployeeDashboard from "./pages/employee/EmployeeDashboard";
import EmployeeViewAllComplaints from "./pages/employee/EmployeeViewAllComplaints";

// manager view: 
import Approvals from "./pages/manager/Approvals";
import ComplaintTrends from "./pages/manager/ComplaintTrends";
import ManagerDashboard from "./pages/manager/ManagerDashboard";
import ManagerViewAllComplaints from "./pages/manager/ManagerViewAllComplaints";
import ViewEmployees from "./pages/manager/ViewEmployees";

// operator view: 
import ChatbotAnalysis from "./pages/operator/ChatbotAnalysis";
import ModelAnalysis from "./pages/operator/ModelAnalysis";
import OperatorDashboard from "./pages/operator/OperatorDashboard";


function App() {
  return (
    <BrowserRouter>
      <Routes>
        <Route path="/" element={<Login />} />

        {/* Customer */}
        <Route path="/customer" element={<Chatbot />} />

        {/* Employee */}
        <Route path="/employee" element={<EmployeeDashboard />} />
        <Route path="/employee/complaints" element={<EmployeeViewAllComplaints />} />
        <Route path="/employee/details/:id" element={<ComplaintDetails />} />
        <Route path="/employee/reports" element={<AutoGeneratedReports />} />

        {/* Manager */}
        <Route path="/manager" element={<ManagerDashboard />} />
        <Route path="/manager/complaints" element={<ManagerViewAllComplaints />} />
        <Route path="/manager/employees" element={<ViewEmployees />} />
        <Route path="/manager/approvals" element={<Approvals />} />
        <Route path="/manager/trends" element={<ComplaintTrends />} />

        {/* Operator */}
        <Route path="/operator" element={<OperatorDashboard />} />
        <Route path="/operator/model-analysis" element={<ModelAnalysis />} />
        <Route path="/operator/chatbot-analysis" element={<ChatbotAnalysis />} />
      </Routes>
    </BrowserRouter>
  );
}

export default App;