"""
=============================================================================
STEP 1: DATASET DEDUPLICATION
=============================================================================

PURPOSE:
    Before any augmentation or model training, we must remove duplicate and
    near-duplicate transcripts from the raw dataset. This is the single most
    important preprocessing step because:

    1. EXACT DUPLICATES cause the model to memorize specific input-output pairs
       rather than learning generalizable sentiment patterns. If the same
       complaint appears 10 times, the model assigns 10x the gradient weight
       to that single example during backpropagation — creating a model that
       performs well on that exact phrasing but fails on novel inputs.

    2. NEAR-DUPLICATES (transcripts differing by punctuation, whitespace, or
       a single word) compound the problem because they produce identical
       proxy labels from the rule-based labeler. The model sees what appears
       to be "different" examples that all map to the same score, which
       flattens the learned decision boundary and reduces discriminative power.

    3. PROXY LABEL AMPLIFICATION: Since our labels are generated by a lexicon-
       matching rule system (not human annotators), duplicates don't just
       repeat — they repeat with zero label variance. Human annotators would
       at least introduce natural scoring variation across duplicates, but
       rule-based systems produce deterministic outputs for identical inputs.

APPROACH:
    Phase A: Remove exact duplicates (identical transcript strings)
    Phase B: Remove near-duplicates using TF-IDF cosine similarity
             - We convert each transcript to a TF-IDF vector
             - Compute pairwise cosine similarity
             - Cluster transcripts above a similarity threshold (0.92)
             - Keep one representative per cluster (the longest transcript,
               as it likely contains the most information)

    We use 0.92 as the threshold because:
    - Below 0.90: Too aggressive — removes legitimately different complaints
      that happen to share vocabulary (e.g., two different AC complaints)
    - Above 0.95: Too lenient — allows near-duplicates that differ only by
      punctuation or filler words to survive
    - 0.92 strikes the balance where transcripts must share >92% of their
      weighted term structure to be considered duplicates

OUTPUT:
    - Deduplicated CSV saved to data/processed/
    - Detailed log of removal statistics for academic documentation

USAGE:
    python step1_deduplicate.py <input_csv> [similarity_threshold]

    Example:
        python step1_deduplicate.py data/raw/Enhanced.csv 0.92

=============================================================================
"""

import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from pathlib import Path
import logging
import time
import json
from typing import Tuple, Dict
from dataclasses import dataclass

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s | %(levelname)-7s | %(message)s',
    datefmt='%H:%M:%S'
)
logger = logging.getLogger(__name__)


# ==============================================================================
# CONFIGURATION
# ==============================================================================

@dataclass
class DeduplicationConfig:
    """
    Validated deduplication configuration.
    
    REASONING for defaults:
    - similarity_threshold=0.92: Empirically, complaint transcripts that share
      >92% TF-IDF cosine similarity are paraphrases of the same complaint.
      This was determined by manual inspection of borderline cases.
    - min_transcript_length=10: Transcripts shorter than 10 characters are
      likely data artifacts (empty strings, single words) and should be
      removed entirely, not just deduplicated.
    """
    input_csv: str
    output_dir: str = 'data/processed'
    similarity_threshold: float = 0.92
    min_transcript_length: int = 10
    
    def __post_init__(self):
        if not Path(self.input_csv).exists():
            raise FileNotFoundError(f"❌ Input file not found: {self.input_csv}")
        if not 0.5 <= self.similarity_threshold <= 0.99:
            raise ValueError(
                f"❌ similarity_threshold must be in [0.5, 0.99], "
                f"got {self.similarity_threshold}"
            )
        if self.min_transcript_length < 0:
            raise ValueError(
                f"❌ min_transcript_length must be >= 0, "
                f"got {self.min_transcript_length}"
            )


# ==============================================================================
# PHASE A: EXACT DEDUPLICATION
# ==============================================================================

def remove_exact_duplicates(df: pd.DataFrame) -> Tuple[pd.DataFrame, Dict]:
    """
    Remove rows with identical transcript text.
    
    REASONING:
        We normalize whitespace and case before comparison because transcripts
        from different sources may have inconsistent formatting. A transcript
        like "The AC is broken" and "the ac is broken" are semantically
        identical and would produce identical proxy labels.
        
        We keep the FIRST occurrence (rather than, say, a random one) to
        ensure reproducibility across runs.
    
    Returns:
        (deduplicated_df, statistics_dict)
    """
    original_count = len(df)
    
    # Normalize for comparison (lowercase, strip whitespace, collapse spaces)
    # but preserve the original text in the dataframe
    df['_normalized'] = (
        df['transcript']
        .astype(str)
        .str.lower()
        .str.strip()
        .str.replace(r'\s+', ' ', regex=True)
    )
    
    # Remove exact duplicates based on normalized text
    df_deduped = df.drop_duplicates(subset='_normalized', keep='first').copy()
    df_deduped = df_deduped.drop(columns=['_normalized'])
    
    removed_count = original_count - len(df_deduped)
    
    stats = {
        'original_count': original_count,
        'after_exact_dedup': len(df_deduped),
        'exact_duplicates_removed': removed_count,
        'exact_duplicate_pct': round(removed_count / original_count * 100, 2)
    }
    
    logger.info(f"Phase A — Exact Deduplication:")
    logger.info(f"  Original:  {original_count}")
    logger.info(f"  Removed:   {removed_count} ({stats['exact_duplicate_pct']}%)")
    logger.info(f"  Remaining: {len(df_deduped)}")
    
    return df_deduped.reset_index(drop=True), stats


# ==============================================================================
# PHASE B: NEAR-DUPLICATE REMOVAL
# ==============================================================================

def remove_near_duplicates(
    df: pd.DataFrame,
    threshold: float = 0.92
) -> Tuple[pd.DataFrame, Dict]:
    """
    Remove near-duplicate transcripts using TF-IDF cosine similarity.
    
    REASONING:
        TF-IDF (Term Frequency–Inverse Document Frequency) converts each
        transcript into a sparse vector where each dimension represents a
        word, weighted by how important that word is to a specific document
        relative to the entire corpus.
        
        Cosine similarity between two TF-IDF vectors measures how similar
        their word usage patterns are, independent of document length. Two
        transcripts about the same complaint using slightly different phrasing
        will have high cosine similarity (>0.92) because they share the same
        domain-specific terms.
        
        We use a GREEDY CLUSTERING approach rather than full pairwise
        comparison because:
        - Full pairwise is O(n²) in memory, which fails on large datasets
        - Greedy clustering processes documents sequentially, marking each
          as either a "cluster representative" or a "duplicate of existing
          cluster", which is O(n × k) where k is the number of clusters
        
        From each cluster of near-duplicates, we keep the LONGEST transcript
        because:
        - Longer transcripts contain more sentiment signal words
        - They provide more context for the model to learn from
        - Shorter near-duplicates are typically truncated versions
    
    Returns:
        (deduplicated_df, statistics_dict)
    """
    original_count = len(df)
    
    if original_count == 0:
        return df, {'near_duplicates_removed': 0}
    
    logger.info(f"\nPhase B — Near-Duplicate Detection (threshold={threshold}):")
    logger.info(f"  Computing TF-IDF vectors...")
    
    # Build TF-IDF matrix
    # REASONING for parameters:
    # - max_features=10000: Limits vocabulary to top 10K terms, reducing noise
    #   from rare misspellings while retaining all meaningful complaint terms
    # - ngram_range=(1,2): Includes bigrams like "air conditioning", "not working"
    #   which are critical domain terms that unigrams alone would miss
    # - min_df=2: A term must appear in at least 2 documents to be included,
    #   filtering out one-off typos and artifacts
    # - sublinear_tf=True: Applies log(1+tf) scaling so a word appearing 10x
    #   in a document doesn't get 10x the weight of appearing once — prevents
    #   long, repetitive complaints from dominating similarity scores
    vectorizer = TfidfVectorizer(
        max_features=10000,
        ngram_range=(1, 2),
        min_df=2,
        sublinear_tf=True,
        strip_accents='unicode',
        lowercase=True
    )
    
    transcripts = df['transcript'].astype(str).tolist()
    tfidf_matrix = vectorizer.fit_transform(transcripts)
    
    logger.info(f"  TF-IDF matrix: {tfidf_matrix.shape}")
    logger.info(f"  Finding near-duplicate clusters...")
    
    # Greedy clustering: process each document, assign to existing cluster
    # or create new cluster
    n_docs = tfidf_matrix.shape[0]
    cluster_labels = [-1] * n_docs  # -1 = unassigned
    cluster_id = 0
    
    # Process in batches for memory efficiency
    # REASONING: Computing full n×n similarity matrix would require
    # O(n²) memory. For 10K documents, that's ~800MB of float64.
    # Batch processing computes similarity of each document against
    # existing cluster representatives only.
    batch_size = 500
    representatives = []  # indices of cluster representative documents
    
    for i in range(n_docs):
        if cluster_labels[i] != -1:
            continue  # Already assigned to a cluster
        
        # This document starts a new cluster
        cluster_labels[i] = cluster_id
        current_cluster = [i]
        
        # Compare against all remaining unassigned documents
        if i + 1 < n_docs:
            # Compute similarity between document i and all subsequent documents
            sim_scores = cosine_similarity(
                tfidf_matrix[i:i+1],
                tfidf_matrix[i+1:]
            )[0]
            
            # Find near-duplicates
            for j_offset, sim in enumerate(sim_scores):
                j = i + 1 + j_offset
                if cluster_labels[j] == -1 and sim >= threshold:
                    cluster_labels[j] = cluster_id
                    current_cluster.append(j)
        
        representatives.append(current_cluster)
        cluster_id += 1
        
        # Progress logging
        if (i + 1) % 1000 == 0:
            logger.info(f"  Processed {i+1}/{n_docs} documents, "
                       f"{cluster_id} clusters found")
    
    # From each cluster, keep the longest transcript
    # REASONING: The longest transcript in a near-duplicate cluster
    # contains the most information. Shorter versions are typically
    # truncated or missing contextual phrases.
    keep_indices = []
    multi_member_clusters = 0
    
    for cluster_members in representatives:
        if len(cluster_members) == 1:
            keep_indices.append(cluster_members[0])
        else:
            multi_member_clusters += 1
            # Keep the longest transcript in this cluster
            lengths = [len(str(df.iloc[idx]['transcript'])) for idx in cluster_members]
            best_idx = cluster_members[np.argmax(lengths)]
            keep_indices.append(best_idx)
    
    # Build deduplicated dataframe
    df_deduped = df.iloc[sorted(keep_indices)].reset_index(drop=True)
    
    removed_count = original_count - len(df_deduped)
    
    stats = {
        'before_near_dedup': original_count,
        'after_near_dedup': len(df_deduped),
        'near_duplicates_removed': removed_count,
        'near_duplicate_pct': round(removed_count / original_count * 100, 2),
        'total_clusters': cluster_id,
        'multi_member_clusters': multi_member_clusters,
        'similarity_threshold': threshold
    }
    
    logger.info(f"  Total clusters: {cluster_id}")
    logger.info(f"  Multi-member clusters: {multi_member_clusters}")
    logger.info(f"  Near-duplicates removed: {removed_count} ({stats['near_duplicate_pct']}%)")
    logger.info(f"  Remaining: {len(df_deduped)}")
    
    return df_deduped, stats


# ==============================================================================
# QUALITY FILTER
# ==============================================================================

def filter_low_quality(
    df: pd.DataFrame,
    min_length: int = 10
) -> Tuple[pd.DataFrame, Dict]:
    """
    Remove transcripts that are too short or empty.
    
    REASONING:
        Transcripts shorter than ~10 characters cannot contain meaningful
        sentiment information. They are typically:
        - Empty strings or NaN values from data collection errors
        - Single words like "okay" or "yes" that carry no complaint context
        - Metadata artifacts that leaked into the transcript column
        
        These samples would:
        - Receive a proxy_sentiment of 0.0 (neutral) by default
        - Add noise to the neutral-sentiment class, making it harder for
          the model to distinguish genuine neutral complaints from garbage
        - Waste training compute on uninformative examples
    """
    original_count = len(df)
    
    # Remove NaN transcripts
    df = df.dropna(subset=['transcript']).copy()
    
    # Remove short transcripts
    df['_len'] = df['transcript'].astype(str).str.strip().str.len()
    df = df[df['_len'] >= min_length].drop(columns=['_len'])
    
    removed_count = original_count - len(df)
    
    stats = {
        'before_quality_filter': original_count,
        'after_quality_filter': len(df),
        'low_quality_removed': removed_count,
        'min_length_threshold': min_length
    }
    
    logger.info(f"\nQuality Filter (min_length={min_length}):")
    logger.info(f"  Removed: {removed_count} low-quality transcripts")
    logger.info(f"  Remaining: {len(df)}")
    
    return df.reset_index(drop=True), stats


# ==============================================================================
# MAIN PIPELINE
# ==============================================================================

def deduplicate_dataset(config: DeduplicationConfig) -> pd.DataFrame:
    """
    Full deduplication pipeline: load → quality filter → exact dedup → near dedup.
    
    Returns:
        Clean, deduplicated DataFrame
    """
    start_time = time.perf_counter()
    
    logger.info("=" * 70)
    logger.info("STEP 1: DATASET DEDUPLICATION")
    logger.info("=" * 70)
    
    # Load
    logger.info(f"\n📂 Loading: {config.input_csv}")
    df = pd.read_csv(config.input_csv)
    logger.info(f"✓ Loaded {len(df)} records")
    
    if 'transcript' not in df.columns:
        raise ValueError(
            f"❌ CSV must have 'transcript' column. "
            f"Found columns: {list(df.columns)}"
        )
    
    initial_count = len(df)
    all_stats = {'initial_count': initial_count}
    
    # Phase 0: Quality filter
    df, quality_stats = filter_low_quality(df, config.min_transcript_length)
    all_stats.update(quality_stats)
    
    # Phase A: Exact deduplication
    df, exact_stats = remove_exact_duplicates(df)
    all_stats.update(exact_stats)
    
    # Phase B: Near-duplicate removal
    df, near_stats = remove_near_duplicates(df, config.similarity_threshold)
    all_stats.update(near_stats)
    
    # Summary
    total_removed = initial_count - len(df)
    all_stats['final_count'] = len(df)
    all_stats['total_removed'] = total_removed
    all_stats['total_removed_pct'] = round(total_removed / initial_count * 100, 2)
    
    # Save
    output_path = Path(config.output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    
    output_csv = output_path / f"deduplicated_n{len(df)}.csv"
    df.to_csv(output_csv, index=False)
    
    stats_file = output_path / "deduplication_stats.json"
    with open(stats_file, 'w') as f:
        json.dump(all_stats, f, indent=2)
    
    elapsed = time.perf_counter() - start_time
    
    logger.info(f"\n{'=' * 70}")
    logger.info(f"DEDUPLICATION COMPLETE")
    logger.info(f"{'=' * 70}")
    logger.info(f"  Initial:     {initial_count}")
    logger.info(f"  Final:       {len(df)}")
    logger.info(f"  Removed:     {total_removed} ({all_stats['total_removed_pct']}%)")
    logger.info(f"  Saved to:    {output_csv}")
    logger.info(f"  Stats:       {stats_file}")
    logger.info(f"  Time:        {elapsed:.1f}s")
    
    return df


# ==============================================================================
# CLI
# ==============================================================================

if __name__ == "__main__":
    import sys
    
    if len(sys.argv) < 2:
        print("\nUsage: python step1_deduplicate.py <input_csv> [similarity_threshold]")
        print("\nExample:")
        print("  python step1_deduplicate.py data/raw/Enhanced.csv 0.92")
        print("\nThis script removes exact and near-duplicate transcripts.")
        print("Run this BEFORE any augmentation or model training.")
        sys.exit(1)
    
    input_csv = sys.argv[1]
    threshold = float(sys.argv[2]) if len(sys.argv) > 2 else 0.92
    
    config = DeduplicationConfig(
        input_csv=input_csv,
        output_dir='data/processed',
        similarity_threshold=threshold
    )
    
    df = deduplicate_dataset(config)
    print(f"\n✅ Deduplication complete: {len(df)} unique records")
